/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsIndexImport } from './routes/projects/index'
import { Route as ProjectsCreateImport } from './routes/projects/create'
import { Route as ProjectsProjectKeyImport } from './routes/projects/$project-key'
import { Route as ProjectsProjectKeyTestSuitesEditImport } from './routes/projects_/$project-key/test-suites/edit'
import { Route as ProjectsProjectKeyTestSuitesCreateImport } from './routes/projects_/$project-key/test-suites/create'
import { Route as ProjectsProjectKeyTestSuitesSuiteIdImport } from './routes/projects_/$project-key/test-suites/$suite-id'
import { Route as ProjectsProjectKeyTestCasesCreateImport } from './routes/projects_/$project-key/test-cases/create'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIndexRoute = ProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsCreateRoute = ProjectsCreateImport.update({
  id: '/projects/create',
  path: '/projects/create',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectKeyRoute = ProjectsProjectKeyImport.update({
  id: '/projects/$project-key',
  path: '/projects/$project-key',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectKeyTestSuitesEditRoute =
  ProjectsProjectKeyTestSuitesEditImport.update({
    id: '/projects_/$project-key/test-suites/edit',
    path: '/projects/$project-key/test-suites/edit',
    getParentRoute: () => rootRoute,
  } as any)

const ProjectsProjectKeyTestSuitesCreateRoute =
  ProjectsProjectKeyTestSuitesCreateImport.update({
    id: '/projects_/$project-key/test-suites/create',
    path: '/projects/$project-key/test-suites/create',
    getParentRoute: () => rootRoute,
  } as any)

const ProjectsProjectKeyTestSuitesSuiteIdRoute =
  ProjectsProjectKeyTestSuitesSuiteIdImport.update({
    id: '/projects_/$project-key/test-suites/$suite-id',
    path: '/projects/$project-key/test-suites/$suite-id',
    getParentRoute: () => rootRoute,
  } as any)

const ProjectsProjectKeyTestCasesCreateRoute =
  ProjectsProjectKeyTestCasesCreateImport.update({
    id: '/projects_/$project-key/test-cases/create',
    path: '/projects/$project-key/test-cases/create',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/projects/$project-key': {
      id: '/projects/$project-key'
      path: '/projects/$project-key'
      fullPath: '/projects/$project-key'
      preLoaderRoute: typeof ProjectsProjectKeyImport
      parentRoute: typeof rootRoute
    }
    '/projects/create': {
      id: '/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof ProjectsCreateImport
      parentRoute: typeof rootRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects_/$project-key/test-cases/create': {
      id: '/projects_/$project-key/test-cases/create'
      path: '/projects/$project-key/test-cases/create'
      fullPath: '/projects/$project-key/test-cases/create'
      preLoaderRoute: typeof ProjectsProjectKeyTestCasesCreateImport
      parentRoute: typeof rootRoute
    }
    '/projects_/$project-key/test-suites/$suite-id': {
      id: '/projects_/$project-key/test-suites/$suite-id'
      path: '/projects/$project-key/test-suites/$suite-id'
      fullPath: '/projects/$project-key/test-suites/$suite-id'
      preLoaderRoute: typeof ProjectsProjectKeyTestSuitesSuiteIdImport
      parentRoute: typeof rootRoute
    }
    '/projects_/$project-key/test-suites/create': {
      id: '/projects_/$project-key/test-suites/create'
      path: '/projects/$project-key/test-suites/create'
      fullPath: '/projects/$project-key/test-suites/create'
      preLoaderRoute: typeof ProjectsProjectKeyTestSuitesCreateImport
      parentRoute: typeof rootRoute
    }
    '/projects_/$project-key/test-suites/edit': {
      id: '/projects_/$project-key/test-suites/edit'
      path: '/projects/$project-key/test-suites/edit'
      fullPath: '/projects/$project-key/test-suites/edit'
      preLoaderRoute: typeof ProjectsProjectKeyTestSuitesEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects/$project-key': typeof ProjectsProjectKeyRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$project-key/test-cases/create': typeof ProjectsProjectKeyTestCasesCreateRoute
  '/projects/$project-key/test-suites/$suite-id': typeof ProjectsProjectKeyTestSuitesSuiteIdRoute
  '/projects/$project-key/test-suites/create': typeof ProjectsProjectKeyTestSuitesCreateRoute
  '/projects/$project-key/test-suites/edit': typeof ProjectsProjectKeyTestSuitesEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects/$project-key': typeof ProjectsProjectKeyRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$project-key/test-cases/create': typeof ProjectsProjectKeyTestCasesCreateRoute
  '/projects/$project-key/test-suites/$suite-id': typeof ProjectsProjectKeyTestSuitesSuiteIdRoute
  '/projects/$project-key/test-suites/create': typeof ProjectsProjectKeyTestSuitesCreateRoute
  '/projects/$project-key/test-suites/edit': typeof ProjectsProjectKeyTestSuitesEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects/$project-key': typeof ProjectsProjectKeyRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects_/$project-key/test-cases/create': typeof ProjectsProjectKeyTestCasesCreateRoute
  '/projects_/$project-key/test-suites/$suite-id': typeof ProjectsProjectKeyTestSuitesSuiteIdRoute
  '/projects_/$project-key/test-suites/create': typeof ProjectsProjectKeyTestSuitesCreateRoute
  '/projects_/$project-key/test-suites/edit': typeof ProjectsProjectKeyTestSuitesEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/projects/$project-key'
    | '/projects/create'
    | '/projects'
    | '/projects/$project-key/test-cases/create'
    | '/projects/$project-key/test-suites/$suite-id'
    | '/projects/$project-key/test-suites/create'
    | '/projects/$project-key/test-suites/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/projects/$project-key'
    | '/projects/create'
    | '/projects'
    | '/projects/$project-key/test-cases/create'
    | '/projects/$project-key/test-suites/$suite-id'
    | '/projects/$project-key/test-suites/create'
    | '/projects/$project-key/test-suites/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/projects/$project-key'
    | '/projects/create'
    | '/projects/'
    | '/projects_/$project-key/test-cases/create'
    | '/projects_/$project-key/test-suites/$suite-id'
    | '/projects_/$project-key/test-suites/create'
    | '/projects_/$project-key/test-suites/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProjectsProjectKeyRoute: typeof ProjectsProjectKeyRoute
  ProjectsCreateRoute: typeof ProjectsCreateRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectKeyTestCasesCreateRoute: typeof ProjectsProjectKeyTestCasesCreateRoute
  ProjectsProjectKeyTestSuitesSuiteIdRoute: typeof ProjectsProjectKeyTestSuitesSuiteIdRoute
  ProjectsProjectKeyTestSuitesCreateRoute: typeof ProjectsProjectKeyTestSuitesCreateRoute
  ProjectsProjectKeyTestSuitesEditRoute: typeof ProjectsProjectKeyTestSuitesEditRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProjectsProjectKeyRoute: ProjectsProjectKeyRoute,
  ProjectsCreateRoute: ProjectsCreateRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectKeyTestCasesCreateRoute:
    ProjectsProjectKeyTestCasesCreateRoute,
  ProjectsProjectKeyTestSuitesSuiteIdRoute:
    ProjectsProjectKeyTestSuitesSuiteIdRoute,
  ProjectsProjectKeyTestSuitesCreateRoute:
    ProjectsProjectKeyTestSuitesCreateRoute,
  ProjectsProjectKeyTestSuitesEditRoute: ProjectsProjectKeyTestSuitesEditRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/projects/$project-key",
        "/projects/create",
        "/projects/",
        "/projects_/$project-key/test-cases/create",
        "/projects_/$project-key/test-suites/$suite-id",
        "/projects_/$project-key/test-suites/create",
        "/projects_/$project-key/test-suites/edit"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/projects/$project-key": {
      "filePath": "projects/$project-key.tsx"
    },
    "/projects/create": {
      "filePath": "projects/create.tsx"
    },
    "/projects/": {
      "filePath": "projects/index.tsx"
    },
    "/projects_/$project-key/test-cases/create": {
      "filePath": "projects_/$project-key/test-cases/create.tsx"
    },
    "/projects_/$project-key/test-suites/$suite-id": {
      "filePath": "projects_/$project-key/test-suites/$suite-id.tsx"
    },
    "/projects_/$project-key/test-suites/create": {
      "filePath": "projects_/$project-key/test-suites/create.tsx"
    },
    "/projects_/$project-key/test-suites/edit": {
      "filePath": "projects_/$project-key/test-suites/edit.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
